- name: Run watchtower
  hosts: all
  tasks:
    - name: Execute an inline Bash script
      shell: |
        #!/bin/bash
        ls -ltr
        cd /projects/docker-watchtower
        docker compose  -f watchtower-compose.yml up --pull always

      register: out

    - debug: var=out.stdout_lines